# Generated by Django 4.1.4 on 2022-12-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_alter_bookmodel_genera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='Release_date',
            field=models.DateField(null=True),
        ),
    ]
