# Generated by Django 4.1.4 on 2022-12-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_alter_bookmodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='Release_date',
            field=models.DateField(),
        ),
    ]
