# Generated by Django 4.1.4 on 2022-12-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_alter_bookmodel_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
